site_name: Galena Wiki
edit_uri: edit/main/docs/
site_url: !ENV [SITE_URL, "http://localhost:8000"]
repo_url: !ENV [REPO_URL]

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo

  logo: assets/icon.svg
  favicon: assets/icon.svg

  features:
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - content.tooltips

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JmMf7CEKsx

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@TeamGalena

    - icon: simple/modrinth
      link: https://modrinth.com/user/TeamGalena

    - icon: fontawesome/brands/github
      link: https://github.com/TeamGalena

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TeamGalena

  hosts:
    icons: https://icons.macarena.ceo/icons

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - pymdownx.snippets

plugins:
  - search
  - markdownextradata:
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
  - glightbox:
      manual: true
  - social:
      enabled: !ENV [CI, false]

extra_css:
  - styles/extra.css
extra_javascript:
  - scripts/favicon.js

not_in_nav: |
  /members.md
  /contributing/**/*.md
